---
- hosts: all
#  pre_tasks:
#    - name: "Installing which"
#      action: yum
#              name=which
#              state=installed
  roles:
    - role: ansible-zabbix-agent
      agent_server: 192.168.3.33
      agent_serveractive: 192.168.3.33
      agent_listenip: 0.0.0.0
