---
- name: remove old install dir
  shell: sudo rm -rf /export/jcloud-cfs/install

- name: copy install.tar.gz
  copy:
    src: "{{ installfile }}"
    dest: "{{ cfsdir }}"

- name: unpackage intall tar file
  unarchive:
    src: "{{ installfile }}"
    dest: "{{ cfsdir }}"

- name: update wos clt wowAdmin
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  with_items:
    - { src: "{{ installdir }}wos-node", dest: "{{ bindir }}" }
    - { src: "{{ installdir }}cfs-clt", dest: "{{ bindir }}" }
    - { src: "{{ installdir }}wos-admin", dest: "{{ bindir }}" }
    - { src: "{{ installdir }}cfs-perf", dest: "{{ bindir }}" }
    - { src: "{{ installdir }}clt-bench", dest: "{{ bindir }}" }
    - { src: "{{ installdir }}gns-bench", dest: "{{ bindir }}" }
    - { src: "{{ installdir }}mds-bench", dest: "{{ bindir }}" }
    - { src: "{{ installdir }}skycli", dest: "{{ bindir }}" }
    - { src: "{{ installdir }}wostool/wos-bench.json", dest: "{{ bindir }}" }
    - { src: "{{ installdir }}wostool/wos-bench", dest: "{{ bindir }}" }
